name: Build nextlib

on:
  workflow_dispatch:

jobs:
  build:
    name: Build nextlib
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build Project with gradle
        run:  |
          chmod +x gradlew
          ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4.5.0
        with:
          name: nextlib-release.aar
          path: ./ffmpeg/output
